name: Customer App CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/customer-app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'apps/customer-app/**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/customer-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js 22
      uses: actions/setup-node@v5
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './apps/customer-app/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run Linter
      run: npm run lint

    - name: Run Tests
      run: npm test
