import { StyleSheet } from 'react-native';
import { typography } from '../../../theme';

export default StyleSheet.create({
  flex: { flex: 1 },
  screen: { flex: 1, backgroundColor: '#070707' },
  root: { flex: 1, backgroundColor: '#070707' },
  scrollContent: { flexGrow: 1, paddingHorizontal: 20, alignItems: 'center' },
  brand: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 16 },
  authCard: {
    width: '100%', maxWidth: 440, padding: 22, borderRadius: 28,
    backgroundColor: 'rgba(22,22,22,0.78)', borderWidth: 1,
    borderColor: 'rgba(255,212,163,0.19)', overflow: 'hidden',
  },
  form: { gap: 8 },
  mt: { marginTop: 14 },
  fieldLabel: { ...typography.labelSmall, color: '#FFF8EF', marginBottom: 2 },
  glassInputWrap: {
    flexDirection: 'row', alignItems: 'center', minHeight: 54, paddingHorizontal: 14,
    borderRadius: 15, borderWidth: 1, borderColor: 'rgba(255,255,255,0.24)',
    backgroundColor: 'rgba(255,255,255,0.055)',
  },
  inputFocused: { borderColor: '#FFBC6B', backgroundColor: 'rgba(255,172,62,0.07)' },
  glassInputText: { ...typography.body, flex: 1, minWidth: 0, color: '#FFF8EF', paddingVertical: 12, fontSize: 16 },
  countryCode: { paddingRight: 12, marginRight: 12, borderRightWidth: 1, borderRightColor: 'rgba(255,255,255,0.2)' },
  countryCodeText: { ...typography.body, color: '#FFF8EF', fontSize: 15, fontWeight: '600' },
  otpTitle: { fontSize: 24, fontWeight: '700', color: '#FFF8EF', letterSpacing: -0.6, marginBottom: 2 },
  otpSubtitle: { ...typography.body, fontSize: 13, lineHeight: 21, color: '#C8C4BE', marginBottom: 12 },
  otpPhone: { fontWeight: '600', color: '#FFF8EF' },
  otpRow: { flexDirection: 'row', gap: 6, width: '100%', marginBottom: 6 },
  otpBox: {
    flex: 1, minWidth: 0, height: 50, borderRadius: 11, borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)', backgroundColor: 'rgba(255,255,255,0.055)',
    textAlign: 'center', fontSize: 20, fontWeight: '600', color: '#FFF8EF', paddingVertical: 0,
  },
  otpBoxFilled: { borderColor: '#FFAC3E', backgroundColor: 'rgba(255,172,62,0.07)' },
  otpActions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 4, marginTop: 6 },
  resendText: { ...typography.bodySmall, fontSize: 12, color: '#FFBD70', fontWeight: '600', paddingVertical: 12 },
  resendDisabled: { color: '#BDB7B0' },
  alertRow: { marginVertical: 4 },
  errorText: { ...typography.caption, color: '#FFA3A3', lineHeight: 18 },
  gradientBtn: { borderRadius: 15, minHeight: 52, paddingVertical: 12, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)' },
  btnInner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
  gradientBtnDisabled: { opacity: 0.45 },
  gradientBtnText: { ...typography.buttonLarge, fontSize: 15, color: '#2B1705', fontWeight: '700' },
  navLink: { ...typography.bodySmall, fontSize: 12, color: '#FFF8EF', fontWeight: '600', paddingVertical: 12 },
  navLinkDisabled: { color: '#8B8680' },
  termsRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginTop: 10, marginBottom: 4 },
  checkbox: { width: 18, height: 18, borderRadius: 5, borderWidth: 1.5, borderColor: '#AAA39A', backgroundColor: 'rgba(255,255,255,0.06)', alignItems: 'center', justifyContent: 'center', marginTop: 1, flexShrink: 0 },
  checkboxChecked: { backgroundColor: '#FFAC3E', borderColor: '#FFAC3E' },
  termsText: { ...typography.caption, color: '#C8C4BE', fontSize: 12, lineHeight: 19 },
  termsLink: { color: '#FFF8EF', textDecorationLine: 'underline', fontWeight: '600' },
});
